on: [push, pull_request]
name: Build PR & Push
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            HUSKY: 0
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install, lint, and build
              run: |
                  npm ci
                  npm run lint
                  npm run build
